# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90fcc7a202dc13e30330482f73aa253e0668ad1459dcbcfa5844601d9a89653abbc7dc8a542c22ca49c937748c7df194b65c65cf37d14f8a7eff644ab324c160

test:
  secret_key_base: 14c7b8041187a4d06770ae49f6700feaee49a5490249f8d414bc80ed397ed81473204dc292d2b1b385f99498e1eb59318f0a0a6612687c5841313f6ebbd37c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
